services:
  - type: web
    name: bels-haven-backend
    runtime: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: gunicorn bels_haven.wsgi:application --bind 0.0.0.0:$PORT --workers 2

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: SECRET_KEY
        sync: false

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce
          property: connectionString

      - key: CORS_ALLOWED_ORIGINS
        value: "https://simple-ecommerce-kappa-khaki.vercel.app"

      - key: CORS_ALLOWED_ORIGIN_REGEXES
        value: "^https://.*\\.vercel\\.app$"

      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com,https://*.vercel.app"

      - key: PAYSTACK_SECRET_KEY
        sync: false

      - key: PAYSTACK_PUBLIC_KEY
        sync: false

      - key: EMAIL_HOST_USER
        sync: false

      - key: EMAIL_HOST_PASSWORD
        sync: false

      - key: ADMIN_EMAIL
        sync: false

      - key: WHATSAPP_NUMBER
        sync: false

      - key: ADMIN_API_KEY
        sync: false

      - key: FRONTEND_URL
        value: "https://simple-ecommerce-kappa-khaki.vercel.app"

      - key: MEDIA_ROOT
        value: /opt/render/project/src/media

    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1